[versions]
javaparser = '3.27.1'
micronaut = "5.0.0-M6"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

javaparser = { module = 'com.github.javaparser:javaparser-core', version.ref = 'javaparser' }
